# See: https://taskfile.dev/api/

version: "3"

tasks:
  generate:
    aliases:
      - generate
    desc: "Generate code from proto files"
    vars:
      OUT: ./pkg/sso
      OUT_ROOT: ./pkg
      SOURCE: proto/sso
    cmds:
      - echo $GREETING
      - rm -Rf {{.OUT_ROOT}} || true
      - mkdir -p {{.OUT}}
      - |
        protoc -I proto {{.SOURCE}}/*.proto \
        --go_out={{.OUT}} \
        --go_opt=paths=source_relative \
        --go-grpc_out={{.OUT}} \
        --go-grpc_opt=paths=source_relative